# Generated by Django 3.2 on 2023-05-11 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230511_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='reviews.review', verbose_name='Рейтинг'),
        ),
    ]
